# .github/workflows/php-tests.yml

name: PHP Tests

on:
  push:
    branches: [ main, interface/neurobrutalism ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: secret
          MYSQL_DATABASE: abs
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - uses: actions/checkout@v3
      
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: pdo, mbstring, ctype, fileinfo, tokenizer, dom, json
          coverage: none

      - name: Install Composer dependencies
        run: composer install -n --prefer-dist

      - name: Copy .env
        run: cp .env.example .env

      - name: Generate application key
        run: php artisan key:generate

      - name: Set up MySQL database
        run: |
           # Drop the database and recreate it
           mysql -h 127.0.0.1 -u root -psecret -e "DROP DATABASE IF EXISTS abs; CREATE DATABASE abs;"

          
        - name: Apply all migration files
          run: | 
            for file in database/migrations/*.php; do \
              if [[ $file != *.php~ ]]; then \
                mysql -h 127.0.0.1 -u root -psecret abs < "$file"
              fi \
            done
          
        - name: Run migrations
          run: php artisan migrate --force

      - name: Run tests
        run: php artisan test --memory=256
        env:
          DB_CONNECTION: mysql
          DB_DATABASE: abs
          DB_USERNAME: root
          DB_PASSWORD: secret
